# Verificar se o site é buildado com sucesso

name: Verificar build do site

on:
  push:
    paths:
      - "Site/**"
      - ".github/workflows/verificar-build-site.yml"
  pull_request:
    paths:
      - "Site/**"
      - ".github/workflows/verificar-build-site.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Obter cópia do repositório
      uses: actions/checkout@v4.2.2

    - name: Usar pNpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: "latest"
    
    - name: Usar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: "pnpm"
        # cache-dependency-path: "Site/pnpm-lock.json"
      
    - name: Instalar dependências
      working-directory: "Site"
      run: pnpm install
    
    - name: Buildar versão de produção
      working-directory: "Site"
      run: pnpm run build
