# Verificar se o site é buildado com sucesso

name: Verificar build do site

on:
  push:
    paths:
      - "Site/**"
      - ".github/workflows/verificar-build-site.yml"
  pull_request:
    paths:
      - "Site/**"
      - ".github/workflows/verificar-build-site.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: pnpm/action-setup@v4.0.0
      with:
        version: "latest"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
        cache-dependency-path: "${{ github.workspace }}/Site/pnpm-lock.yaml"
    - name: Build release
      working-directory: "${{ github.workspace }}/Site"
      run: pnpm run build
    - uses: actions/checkout@v4

    
